# Generated by Django 4.0.7 on 2023-06-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('spot_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['track_id'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('track', models.ManyToManyField(related_name='playlists', to='chartify.track')),
            ],
            options={
                'ordering': ['playlist_id'],
            },
        ),
    ]
