# Generated by Django 4.0.7 on 2023-08-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartify', '0002_playlist_last_chart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='last_chart_id',
        ),
    ]
